@echo off
echo Starting Idea Hub Backend...
echo.
cd packages\backend
echo Running Prisma generate...
call npx prisma generate
echo.
echo Running database migrations...
call npx prisma migrate dev --name init
echo.
echo Starting backend server...
call npm run dev
